### ISSUE TITLE
Homepage - Social Media - Twitter id used is not the client's id

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Rare-Parts#122]
![image](https://cloud.githubusercontent.com/assets/12791909/12470050/078896b0-c02c-11e5-98b0-b73aba8b2d3a.png)

**Comment by suniltitan** [comment]
I don't have client twitter id that's why i am adding that link temporarily.If you have client id  give to me i will add that id in home page,other wise you can also add that  id in home page.
![twitter id screen shot](https://cloud.githubusercontent.com/assets/14212899/12614003/33b4c6ae-c523-11e5-9d9d-121634ed6cac.png)

**Comment by ermatitan** [comment]
you can used the titan id https://twitter.com/titan_web

**Comment by suniltitan** [comment]
Hi Erma,
Salman had a discussion with Bernard on this and updated that the functionality is already there and working fine, however it could be tested by anyone's twitter account. If you want you can test it from your twitter id by inserting the twitter widget ID and put in the cms, it should work.

Please let me know the outcome.

**Comment by ermatitan** [comment]
Hello Sunil, 

As per conversation with Bernard today, he said that it is ok to add your personal account to ensure that  the functionality is working fine but should be deleted before returning to QA. Thanks
